// Generated by OABuilder 
package com.template.view.client.panel.template;

import java.util.logging.Logger;

public class TemplatePanel extends TemplatePanelBase {
    private static Logger LOG = Logger.getLogger(TemplatePanel.class.getName());
}
