// Generated by OABuilder 02/13/19 10:13 AM

package com.template.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.template.model.*;
import com.template.model.oa.*;
import com.template.model.oa.propertypath.*;
import com.template.delegate.*;
import com.template.delegate.oa.*;
import com.template.resource.Resource;
import com.template.view.*;

public class AppServerJfc extends AppServerJfcBase {
    
    public AppServerJfc() {
    }
    
    public AppServerJfc(Hub<AppServer> hubAppServer) {
        super(hubAppServer);
    }
    
    public AppServerJfc(AppServerModel modelAppServer) {
        super(modelAppServer);
    }
    
    
    // CUSTOM code here
    
}

