// Generated by OABuilder 

package com.template.view.oa;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.awt.Dialog.*;
import java.lang.ref.WeakReference;
import java.util.*;
import java.util.Map.Entry;
import java.util.logging.*;
import java.util.concurrent.atomic.AtomicInteger;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.text.*;
import javax.swing.event.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.OAButton.*;
import com.viaoa.jfc.border.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.table.*;
import com.viaoa.jfc.text.*;
import com.viaoa.image.*;
import com.viaoa.jfcapp.*;
import com.viaoa.util.*;

import com.template.model.*;
import com.template.model.search.*;
import com.template.model.oa.ReportClass;
import com.template.model.oa.*;
import com.template.model.oa.propertypath.*;
import com.template.model.oa.custom.*;
import com.template.model.oa.filter.*;
import com.template.delegate.*;
import com.template.delegate.oa.*;
import com.template.resource.Resource;
import com.template.view.*;

public class ReportClassJfcBase implements OAModelJfcInterface {
    protected static Logger LOG = Logger.getLogger(ReportClassJfc.class.getName());
    
    public static final String PP_Display    = OAString.cpp(ReportClass.P_Name);
    public static final String PP_Icon       = null;
    public static final String PP_Image      = null;
    public static final String PP_ForeColor  = null;
    public static final String PP_BackColor  = null;
    public static final String PP_IconColor  = null;
    public static final String PP_Font       = null;
    // Model
    protected ReportClassModel model;
    
    // Tree
    protected OATreeNode lastTreeNode;  // used by getTreeUsed()
    protected OATreeTitleNode titleNode;
    protected OATreeNode node;
    
    // ComboBox
    protected OAComboBox cbo;
    protected OATableComboBox cboTable;
    
    // List
    protected OAList lst;
    
    // edit dialog
    private WeakReference<JDialog> wrEditDialog;
    
    // Card Panel
    public static final String CARD_List = "list";
    public static final String CARD_Edit = "edit";
    protected static final String CARD_ReportDefs = "ReportDefs";
    protected int TAB_ReportDefs = -1;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected JTabbedPane tabbedPane;
    
    // Search
    protected ReportClassSearchJfc jfcSearch;
    // hub Search
    protected ReportClassSearchJfc jfcSearchHub;
    // Add
    protected ReportClassSearchJfc jfcAdd;
    
    
    // focus components
    protected OADateTimeTextField dttxtCreated;
    protected OADateTimeTextField tableDtTxtCreated;
    protected ReportDefJfc jfcReportDefs;
    
    public ReportClassJfcBase() {
        this.model = new ReportClassModel();
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    
    public ReportClassJfcBase(Hub<ReportClass> hubReportClass) {
        this.model = new ReportClassModel(hubReportClass);
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    public ReportClassJfcBase(ReportClassModel modelReportClass) {
        if (modelReportClass == null) this.model = new ReportClassModel();
        else this.model = modelReportClass;
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    
    // Hub
    public Hub<ReportClass> getHub() {
        return model.getHub();
    }
    
    private int level;
    public int getLevel() {
        return this.level;
    }
    public void setLevel(int level) {
        this.level = level;
    }
    
    
    // Model
    public ReportClassModel getModel() {
        return model;
    }
    
    
    
    // Images
    public static Icon getIcon() {
        return Resource.getJarIcon("reportClass.gif");
    }
    public static Icon getTitleIcon() {
        return Resource.getJarIcon("reportClasses.gif");
    }
    
    // Tree
    public OATree getTreeUsed() {
        if (lastTreeNode != null) return lastTreeNode.getTree();
        return null;
    }
    protected void setLastTreeNode(OATreeNode tn) {
        if (lastTreeNode == null || lastTreeNode.getTree() == null) {
            lastTreeNode = tn;
        }
    }
    public OATreeTitleNode getTreeTitleNode() {
        if (titleNode == null) {
            titleNode = createTreeTitleNode();
        }
        return titleNode;
    }
    
    public OATreeTitleNode createTreeTitleNode() {
        OATreeTitleNode treeTitleNode = new OATreeTitleNode(getModel().getPluralDisplayName()) {
            @Override
            public void objectSelected(Object obj) {
                super.objectSelected(obj);
                onShowListPanel();
            }
            JLabel lbl;
            @Override
            public Component getTreeCellRendererComponent(Component comp,
                JTree tree, Object value, boolean selected,
                boolean expanded, boolean leaf, int row, boolean hasFocus)
            {
                comp = super.getTreeCellRendererComponent(comp, tree, value, selected, expanded, leaf, row, hasFocus);
                if (lbl == null) {
                    if (comp instanceof JLabel) lbl = (JLabel) comp;
                }
                if (lbl != null) lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
                return comp;
            }
        };
        treeTitleNode.setIcon(getTitleIcon());
        treeTitleNode.setPopupMenu(createTreeTitleNodePopupMenu(treeTitleNode));
        treeTitleNode.setMaxImageHeight(20);
        treeTitleNode.setMaxImageWidth(32);
        setLastTreeNode(treeTitleNode);
        return treeTitleNode;
     }
    
    public JPopupMenu createTreeTitleNodePopupMenu(OATreeNode tn) {
        JPopupMenu menu = new JPopupMenu();
    
        JMenuItem miSearch = createSearchMenuItem();
        if (miSearch != null) menu.add(miSearch);
        JMenuItem miNew = createNewMenuItem();
        if (miNew != null) menu.add(miNew);
        JMenuItem miInsert = createInsertMenuItem();
        if (miInsert != null) menu.add(miInsert);
        if (miSearch != null || miNew != null) menu.addSeparator();
        JMenuItem miPaste = createPasteMenuItem();
        if (miPaste != null) {
            menu.add(miPaste);
            menu.addSeparator();
        }
    
        menu.add(createCollapseOthersMenuItem(tn));
        return menu;
    }
    
    public OAMenuItem createAddMenuItem() {
        if (!getModel().getAllowAdd()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAButton.ADD_MANUAL) {
            @Override
            public boolean onActionPerformed() throws Exception {
                ReportClassJfcBase.this.onAdd();
                return true;
            }
        };
        mi.setText("Add a "+getModel().getDisplayName());
        mi.setToolTipText("Add a "+getModel().getDisplayName());
        return mi;
    }
    
    public OAMenuItem createNewMenuItem() {
        return createNewMenuItem(getHub());
    }
    public OAMenuItem createNewMenuItem(Hub<ReportClass> hub) {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(hub, OAMenuItem.NEW) {
            @Override
            public void afterActionPerformed() {
                // ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                ReportClassJfcBase.this.onNewReportClassCreated();
                super.afterActionPerformed();
            }
        };
        mi.setMnemonic(KeyEvent.VK_N);
        mi.setText("Create a new "+getModel().getDisplayName());
        mi.setToolTipText("Create a new "+getModel().getDisplayName());
        mi.setFocusComponent(dttxtCreated);
        return mi;
    }
    
    public OAMenuItem createInsertMenuItem() {
        return createInsertMenuItem(getHub());
    }
    public OAMenuItem createInsertMenuItem(Hub<ReportClass> hub) {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(hub, OAMenuItem.INSERT) {
            @Override
            public void afterActionPerformed() {
                // ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                ReportClassJfcBase.this.onNewReportClassCreated();
                super.afterActionPerformed();
            }
        };
        mi.setMnemonic(KeyEvent.VK_I);
        mi.setText("Insert a new "+getModel().getDisplayName());
        mi.setToolTipText("Insert a new "+getModel().getDisplayName());
        mi.setFocusComponent(dttxtCreated);
        return mi;
    }
    
    public JMenuItem createCollapseOthersMenuItem(final OATreeNode tn) {
        JMenuItem mi = new JMenuItem();
        mi.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                OATree t = tn.getTree();
                if (t != null) {
                    t.expandOnlySelectedTreeNode();
                }
            }
        });
        mi.setMnemonic(KeyEvent.VK_C);
        mi.setText("Collapse others");
        mi.setToolTipText("Collapse other tree nodes");
        return mi;
    }
    public OATreeNode getTreeNode() {
        if (node != null) return node;
        node = createTreeNode(null, null, true);
        return node;
    }
    public OATreeNode createTreeNode(String leadingPropertyPath, Hub<ReportClass> hubRoot, boolean bIncludeChildren, OATreeNode ... parentNodes) {
        if (hubRoot == null && OAString.isEmpty(leadingPropertyPath)) {
            hubRoot = getModel().getHub();
        }
        OATreeNode node = new OATreeNode(OAString.cpp(leadingPropertyPath, ReportClass.P_Name), hubRoot, getHub()) {
            @Override
            public void objectSelected(Object obj) {
                super.objectSelected(obj);
                ReportClassJfcBase.this.getCardPanel();
                ReportClassJfcBase.this.onShowEditPanel();
            }
            @Override
            public void onDoubleClick(Object obj, MouseEvent e) {
                ReportClassJfcBase.this.onDoubleClickTreeNode();
            }
            @Override
            public JPopupMenu getPopupMenu() {
                JPopupMenu pm = super.getPopupMenu();
                if (pm == null) {
                    pm = createTreeNodePopupMenu(this);
                    setPopupMenu(pm);
                }
                return pm;
            }
        };
        node.setIcon(getIcon());
        node.setForegroundColorProperty(PP_ForeColor);
        node.setBackgroundColorProperty(PP_BackColor);
        node.setIconColorProperty(PP_IconColor);
        node.setImageProperty(PP_Icon);
        node.setAllowDnD(true);
        node.setAllowDrop(true);
        node.setAllowDrag(true);
        node.setFontProperty(PP_Font);
        node.setSuffix(null);
        node.setMaxImageHeight(20);
        node.setMaxImageWidth(32);
        setLastTreeNode(node);
        if (getModel().getAllowMultiSelect()) {
            node.setSelectedHub(getModel().getMultiSelectHub());
        }
    
        if (!bIncludeChildren) {
            return node;
        }
     
        OATreeNode[] nodes = (OATreeNode[]) OAArray.add(OATreeNode.class, parentNodes, node);
        OATreeTitleNode ttn;
        OATreeNode node2;
        ttn = getReportDefsJfc().getTreeTitleNode();
        node2 = findNode(ReportClass.P_ReportDefs, parentNodes);
        if (node2 == null) {
            node2 = getReportDefsJfc().createTreeNode(ReportClass.P_ReportDefs, null, true, nodes);
            node2.setAllowDnd(false);
        }
        ttn.add(node2);
        node.add(ttn);
     
        return node;
    }
    protected OATreeNode findNode(String propertyPath, OATreeNode ... parentNodes) {
        if (propertyPath == null) return null;
        for (OATreeNode tn : parentNodes) {
            if (tn.getHub() != null) continue;
            String pp = tn.getPropertyPath();
            if (pp == null) continue;
            if (pp.toLowerCase().startsWith(propertyPath.toLowerCase()+".")) return tn;
        }
        return null;
    }
    
    public JPopupMenu createTreeNodePopupMenu(OATreeNode tn) {
        JPopupMenu menu = new JPopupMenu();
    
        JMenuItem miSearch = createSearchMenuItem();
        if (miSearch != null) menu.add(miSearch);
        JMenuItem miNew = createNewMenuItem();
        if (miNew != null) menu.add(miNew);
        JMenuItem miInsert = createInsertMenuItem();
        if (miInsert != null) menu.add(miInsert);
        if (miSearch != null || miNew != null) menu.addSeparator();
    
        OAMenuItem mi;
        mi = getReportDefsJfc().createNewMenuItem();
        if (mi != null) menu.add(mi);
        mi = getReportDefsJfc().createAddMenuItem();
        if (mi != null) menu.add(mi);
    
        menu.addSeparator();
        JMenuItem miRemove = createRemoveMenuItem();
        if (miRemove != null) menu.add(miRemove);
        JMenuItem miDelete = createDeleteMenuItem();
        if (miDelete != null) menu.add(miDelete);
    
        if (miRemove != null || miDelete != null) menu.addSeparator();
        JMenuItem miCut = createCutMenuItem();
    
        if (miCut != null) menu.add(miCut);
        JMenuItem miCopy = createCopyMenuItem();
        if (miCopy != null) menu.add(miCopy);
        JMenuItem miPaste = createPasteMenuItem();
        if (miPaste != null) menu.add(miPaste);
    
        if (miCut != null || miCopy != null || miPaste != null) menu.addSeparator();
    
        JMenuItem miCollapse = createCollapseOthersMenuItem(tn);
        if (miCollapse != null) menu.add(miCollapse);
    
        return menu;
    }
    public OAMenuItem createSearchMenuItem() {
        if (!getModel().getAllowSearch()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), getModel().getDisplayName() + " search ...", Resource.getJarIcon("search.gif"), OAButton.SEARCH) {
            @Override
            public Object getSearchObject() {
                ReportClass reportClass = ReportClassJfcBase.this.onSearch();
                return reportClass;
            }
            @Override
            public void afterActionPerformed() {
                super.afterActionPerformed();
                OATree tree = getTreeUsed();
                if (tree != null) {
                    tree.setSelectedNode(getHub().getAO());
                }
                onShowEditPanel();
            }
        };
        mi.setMnemonic(KeyEvent.VK_S);
        return mi;
    }
    
    public JMenuItem createHubSearchMenuItem() {
        if (!getModel().getAllowHubSearch()) return null;
        JMenuItem mi = new JMenuItem(getModel().getDisplayName() + " table search ...", Resource.getJarIcon("hubsearch16.png"));
        mi.setMnemonic(KeyEvent.VK_I);
        mi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ReportClassJfcBase.this.onHubSearch();
           }
        });
        return mi;
    }
    public OAMenuItem createCutMenuItem() {
        if (!getModel().getAllowCut()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.CUT);
        mi.setText("Cut "+getModel().getDisplayName());
        if (getModel().getAllowMultiSelect()) {
            mi.setMultiSelectHub(getModel().getMultiSelectHub());
        }
        return mi;
    }
    public OAMenuItem createCopyMenuItem() {
        if (!getModel().getAllowCopy()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.COPY);
        mi.setText("Copy "+getModel().getDisplayName());
        mi.setToolTipText("Create a copy of "+getModel().getDisplayName());
        if (getModel().getAllowMultiSelect()) {
            mi.setMultiSelectHub(getModel().getMultiSelectHub());
        }
        return mi;
    }
    public OAMenuItem createPasteMenuItem() {
        if (!getModel().getAllowPaste()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.PASTE);
        mi.setText("Paste "+getModel().getDisplayName());
        mi.setToolTipText("Paste "+getModel().getDisplayName());
        mi.setConfirmMessage("Ok to paste?");
        return mi;
    }
    public OAMenuItem createSaveMenuItem() {
        if (!getModel().getAllowSave()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.SAVE);
        mi.setText("Save "+getModel().getDisplayName());
        mi.setMnemonic(KeyEvent.VK_S);
        mi.setToolTipText("Save "+getModel().getDisplayName());
        return mi;
    }
    public OAMenuItem createDeleteMenuItem() {
        if (!getModel().getAllowDelete()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.DELETE);
        mi.setText("Delete "+getModel().getDisplayName()+" ...");
        mi.setConfirmMessage("OK to Delete this "+getModel().getDisplayName()+" from system?");
        mi.setMnemonic(KeyEvent.VK_D);
        mi.setUseSwingWorker(true);
        mi.setProcessingText("Processing ...", "Please wait while deleting Client");
        // mi.setToolTipText("Delete "+getModel().getDisplayName()+" from system, must be an Admin to do this.");
        return mi;
    }
    public OAMenuItem createRemoveMenuItem() {
        if (!getModel().getAllowRemove()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.REMOVE);
        mi.setText("Remove "+getModel().getDisplayName()+" ...");
        mi.setToolTipText("remove "+getModel().getDisplayName()+" from the list");
        mi.setMnemonic(KeyEvent.VK_R);
        return mi;
    }
    
    // Label
    public OALabel createLabel() {
        OALabel lbl = new OALabel(getHub(), OAString.cpp(ReportClass.P_Name), 18) {
            @Override
            public void customizeRenderer(JLabel lbl, Object object, Object value, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
                ReportClassJfcBase.this.customizeRenderer(lbl, ReportClassJfcBase.this.getHub().getAt(row), isSelected, hasFocus, row, wasChanged, wasMouseOver);
            }
            @Override
            public String getToolTipText(Object object, int row, String defaultValue) {
                return ReportClassJfcBase.this.getToolTipText(ReportClassJfcBase.this.getHub().getAt(row), row, defaultValue);
            }
        };
        lbl.setMaximumColumns(55);
        lbl.setMinimumColumns(9);
        lbl.setIconColorProperty(PP_IconColor);
        lbl.setImageProperty(PP_Icon);
        lbl.setFormat(null);
        lbl.setMaxImageHeight(20);
        lbl.setMaxImageWidth(32);
        lbl.setVerticalAlignment(SwingConstants.TOP);
        return lbl;
    }
    // used for Label, ComboBox
    protected void customizeRenderer(JLabel lbl, ReportClass reportClass, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
    }
    protected String getToolTipText(ReportClass reportClass, int row, String defaultValue) {
        return defaultValue;
    }
    
    // ComboBox
    public OAComboBox getComboBox() {
        if (cbo == null) {
            cbo = createComboBox();
        }
        return cbo;
    }
    
    public OAComboBox createComboBox() {
        OAComboBox cbo = new OAComboBox(getHub(), OAString.cpp(ReportClass.P_Name), 18) {
            @Override
            public void customizeRenderer(JLabel lbl, Object object, Object value, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
                ReportClassJfcBase.this.customizeRenderer(lbl, ReportClassJfcBase.this.getHub().getAt(row), isSelected, hasFocus, row, wasChanged, wasMouseOver);
            }
            @Override
            public String getToolTipText(Object object, int row, String defaultValue) {
                return ReportClassJfcBase.this.getToolTipText(ReportClassJfcBase.this.getHub().getAt(row), row, defaultValue);
            }
        };
    
        cbo.setPopupColumns(33);
        cbo.setMaximumRowCount(15);
        cbo.setMaximumColumns(55);
        cbo.setMinimumColumns(9);
        cbo.setIconColorProperty(PP_IconColor);
        cbo.setImageProperty(PP_Icon);
        cbo.setFormat(null);
        cbo.setNullDescription("<html><i style='color:gray'>select</i></html>]");
        cbo.setMaxImageHeight(20);
        cbo.setMaxImageWidth(32);
        return cbo;
    }
    
    public OATableComboBox getTableComboBox() {
        if (cboTable == null) {
            cboTable = createTableComboBox();
        }
        return cboTable;
    }
    public OATableComboBox createTableComboBox() {
        OATable table = new OATable(getHub());
        table.setAllowDnD(false);
        table.setAllowSorting(false);
        table.addCounterColumn();
        getSearchJfc().createTableColumns(table);
        table.setPreferredSize(15, 4, true);
        table.resizeColumnsToFitHeading();
        
        OATableComboBox cboTable = new OATableComboBox(table, getHub(), PP_Display) {
            @Override
            public void onClear() {
                getHub().setAO(null);
            }
        };
        cboTable.allowClearButton(true);
        cboTable.setIconColorProperty(PP_IconColor);
        cboTable.setColumns(18);
        cboTable.setMaximumColumns(55);
        return cboTable;
    }
    
    
    // List
    public OAList getList() {
        if (lst == null) {
            lst = createList();
        }
        return lst;
    }
    public OAList createList() {
        OAList lst = new OAList(getHub(), OAString.cpp(ReportClass.P_Name), 12, 18) {
            @Override
            public void customizeRenderer(JLabel label, JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.customizeRenderer(label, list, value, index, isSelected, cellHasFocus);
                ReportClassJfcBase.this.customizeRenderer(label, ReportClassJfcBase.this.getHub().getAt(index), isSelected, cellHasFocus, index, false, false);
            }
        };
        lst.setMinimumColumns(6);
        lst.setMaximumColumns(55);
        lst.setAllowDnD(true);
        lst.setAllowRemove(true);
        lst.setAllowDelete(false);
        lst.setAllowInsert(false);
        lst.setImageProperty(null);
        lst.setMaxImageHeight(20);
        lst.setMaxImageWidth(32);
        lst.setIconColorProperty(PP_IconColor);
        lst.setBackgroundColorProperty(null);
        lst.setDoubleClickButton(null);
        if (model.getAllowMultiSelect()) {
            lst.setSelectionHub(getModel().getMultiSelectHub());
        }
        lst.setBorder(new EmptyBorder(3,3,1,1));
        
        return lst;
    }
    
    public JPanel createGrowingList() {
        OAList lst = createList();
        lst.setVisibleRowCount(1);
        lst.setBorder(new LineBorder(Color.gray, 1));
        
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(lst);
        
        JPanel panx = new JPanel(new FlowLayout(FlowLayout.LEFT, 2, 0));
        
        OAButton cmd = createGotoEditButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createAddButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createNewButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createDeleteButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createRemoveButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createRefreshButton();
        if (cmd != null) panx.add(cmd);
        
        pan.add(panx, BorderLayout.SOUTH);
        return pan;
    }
    // comboBoxTree
    public OATreeComboBox createSearchTreeComboBox() {
        OATreeComboBox cbo = new OATreeComboBox(createSearchTree(), getHub(), PP_Display);
        cbo.setColumns(18);
        return cbo;
    }
    public OATree createSearchTree() {
        OATree tree = new OATree();
        tree.setPreferredSize(10, 22);
        OATreeTitleNode tnode;
        OATreeNode node, node2;
    
        tnode = new OATreeTitleNode(getModel().getPluralDisplayName());
        tnode.setIcon(ReportClassJfc.getTitleIcon());
        tree.add(tnode);
        node = new OATreeNode(ReportClassJfc.PP_Display, ModelDelegate.getReportClasses().createSharedHub(), getHub()) {
            @Override
            public void onDoubleClick(Object obj, MouseEvent e) {
                ReportClassJfcBase.this.onDoubleClickTreeNode();
            }
        };
        if (getModel().getAllowMultiSelect()) {
            node.setSelectedHub(getModel().getMultiSelectHub());
        }
        node.setIcon(ReportClassJfc.getIcon());
        node.setForegroundColorProperty(ReportClassJfc.PP_ForeColor);
        node.setBackgroundColorProperty(ReportClassJfc.PP_BackColor);
        node.setIconColorProperty(ReportClassJfc.PP_IconColor);
        node.setImageProperty(ReportClassJfc.PP_Icon);
        node.setFontProperty(ReportClassJfc.PP_Font);
        node.setMaxImageHeight(20);
        node.setMaxImageWidth(32);
        tnode.add(node);
        return tree;
    }
    
    
    // Table
    public JPanel createTablePanel() {
        return createTablePanel(true, true);
    }
    public JPanel createTablePanel(boolean bIncludeNorthToolbar, boolean bIncludeSouthToolbar) {
        OATable table = createTable();
        // table.setSelectHub(getModel().getMultiSelectHub());
    
        OATableScrollPane tableScrollPane = createTableScrollPane(table);
        tableScrollPane.setBorder(new TitledBorder(""));
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(tableScrollPane, BorderLayout.CENTER);
        
        if (bIncludeNorthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createTableFindToolBar());
            if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.NORTH);
        }
        if (bIncludeSouthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createSouthTableToolBar());
            if (toolBar != null) {
                pan.add(new OAScroller(toolBar), BorderLayout.SOUTH);
            }
        }
        return pan;
    }
    public JPanel createReadOnlyTablePanel() {
        OATable table = createReadOnlyTable();
        // table.setSelectHub(getModel().getMultiSelectHub());
    
        OATableScrollPane tableScrollPane = createTableScrollPane(table);
        tableScrollPane.setBorder(new TitledBorder(""));
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(tableScrollPane, BorderLayout.CENTER);
        
        JToolBar toolBar = createToolBar(ToolBarOptions.createSouthTableToolBar());
        if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.SOUTH);
        
        return pan;
    }
    public JPanel createCombinedPanel() {
        return createCombinedPanel(false); 
    }
    protected boolean bHasCombinedPanel;
    public JPanel createCombinedPanel(final boolean bUseList) {
        bHasCombinedPanel = true;
        JTabbedPane tp;
        Dimension d = new Dimension(5,5);
        if (this.tabbedPane == null) tp = getTabbedPane();
        else tp = createTabbedPane();
        tp.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        if (this.tabbedPane == null) tp = getTabbedPane();
        final JComponent comp = createEditPanel(tp, false);
        comp.setMinimumSize(d);
        JSplitPane splitPane = new OASplitPane(bUseList ? JSplitPane.HORIZONTAL_SPLIT : JSplitPane.VERTICAL_SPLIT,
                bUseList ? new JScrollPane(createList()) : createTableScrollPane(createTable()), 
                comp
        ) {
            @Override
            public void addNotify() {
                super.addNotify();
                Dimension d = getSize();
                Dimension d2 = comp.getPreferredSize();
                if (!bUseList && d2.height > d.height) {
                    setResizeWeight(.25);
                }
                if (!bUseList && getLevel() > 1) setDividerLocation(9999);
            }
        };
        
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(bUseList ? .0 : .95);
        
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(splitPane, BorderLayout.CENTER);
        
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createTableToolBar())), BorderLayout.NORTH);
        return pan;
    }
    
    public JPanel createSplitPanel(int splitType, ToolBarOptions tbOptions, JComponent compTop, JComponent compBottom) {
        compBottom.setMinimumSize(new Dimension(5,5));
        JSplitPane splitPane = new OASplitPane(splitType, compTop, compBottom) {
            @Override
            public void addNotify() {
                super.addNotify();
                Dimension d = getSize();
                Dimension d2 = compBottom.getPreferredSize();
                if (splitType == JSplitPane.VERTICAL_SPLIT && d2.height > d.height) {
                    setResizeWeight(.25);
                }
                if (splitType == JSplitPane.VERTICAL_SPLIT && getLevel() > 1) setDividerLocation(9999);
            }
        };
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(splitPane, BorderLayout.CENTER);
        if (tbOptions != null) pan.add(new OAScroller(createToolBar(tbOptions)), BorderLayout.NORTH);
        return pan;
    }
    
    public JPopupMenu createTablePopupMenu() {
        JPopupMenu pmenu = new JPopupMenu();
        OAMenuItem mi = createGotoEditMenuItem();
        if (mi != null) pmenu.add(mi);
    
        mi = createTableNewMenuItem();
        if (mi != null) {
            mi.setFocusComponent(tableDtTxtCreated);
            pmenu.add(mi);
        }
        mi = createInsertMenuItem();
        if (mi != null) {
            mi.setFocusComponent(tableDtTxtCreated);
            pmenu.add(mi);
        }
    
        mi = createSaveMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createRemoveMenuItem();
        if (mi != null) {
            pmenu.add(mi);
            pmenu.addSeparator();
        }
        mi = createDeleteMenuItem();
        if (mi != null) {
            pmenu.add(mi);
            pmenu.addSeparator();
        }
        mi = createCutMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createCopyMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createPasteMenuItem();
        if (mi != null) pmenu.add(mi);
        return pmenu;
    }
    
    public OAMenuItem createGotoEditMenuItem() {
        if (!getModel().getAllowGotoEdit()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), "Details ...", Resource.getJarIcon(Resource.IMG_Goto)) {
            @Override
            public boolean onActionPerformed() throws Exception {
                ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                return true;
            }
        };
        mi.setMnemonic(KeyEvent.VK_G);
        return mi;
    }
    
    public OAMenuItem createTableNewMenuItem() {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.NEW);
        mi.setMnemonic(KeyEvent.VK_N);
        mi.setText("Create a new "+getModel().getDisplayName());
        mi.setFocusComponent(tableDtTxtCreated);
        return mi;
    }
    
    public OATableScrollPane createTableScrollPane(OATable table) {
        OATableScrollPane spTable = new OATableScrollPane(table, 1); // set number of fixed columns
        return spTable;
    }
    protected String getToolTipText(OATable table, int row, int col, String defaultValue) {
        // ReportClass client = (ReportClass) table.getHub().getAt(row);
        // defaultValue = ReportClassDelegate.getToolTipText(client, true);
        return defaultValue;
    }
    public OATable createTable() {
        Hub<ReportClass> hubTable;
        if (getModel().getAllowTableFilter()) hubTable = new Hub<ReportClass>(ReportClass.class);
        else hubTable = getModel().getHub();
     
        OATable table = new OATable(hubTable) {
            @Override
            public void customizeRenderer(JLabel lbl, Object value, boolean isSelected, boolean hasFocus, int row, int column, boolean wasChanged, boolean wasMouseOver) {
            }
            @Override
            public String getToolTipText(int row, int col, String defaultValue) {
                defaultValue = super.getToolTipText(row, col, defaultValue);
                return defaultValue;
            }
            @Override
            public void onDoubleClick() {
                if (ReportClassJfcBase.this.getModel().getAllowGotoEdit()) {
                    ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                }
            }
        };
     
        // table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        if (hubTable != getModel().getHub()) {
            table.setMasterFilterHub(getModel().getHub());
        }
        table.setAllowDnD(false);
        table.setAllowSorting(getModel().getAllowTableSorting());
        // table.setColumnProperties(ModelDelegate.getProperties(), "ReportClass");
    
        table.addCounterColumn();
        if (getModel().getAllowMultiSelect()) {
            table.addSelectionColumn(getModel().getMultiSelectHub(), "Select", 5);
        }
        createTableColumns(table);
        
        table.setPreferredSize(3, 2, true);
        table.setShowChanges(true);
        table.resizeColumnsToFitHeading();
        table.setComponentPopupMenu(createTablePopupMenu());
        return table;
    }
    
    public void createTableColumns(OATable table) {
        OALabel lbl;
        OATableColumn tc;
        tc = table.addColumn("Name", 18, createNameTextField());
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(ReportClass.P_Name));
        }
        tc = table.addColumn("Class Name", 18, createClassNameTextField());
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(ReportClass.P_ClassName));
        }
        if (getModel().getReportDefsModel().getCreateUI()) {
            lbl = new OALabel(getHub(), OAString.cpp(ReportClass.P_ReportDefs, ReportDef.P_Name));
            tc = table.addColumn("Report Defs", 34, lbl);
            if (getModel().getAllowTableFilter()) {
                tc.setFilterComponent(new OATextFieldFilter(OAString.cpp(ReportClass.P_ReportDefs, ReportDef.P_Name)));
            }
        }
    }
    
    public OATable createReadOnlyTable() {
        Hub<ReportClass> hubTable;
        if (getModel().getAllowTableFilter()) hubTable = new Hub<ReportClass>(ReportClass.class);
        else hubTable = getModel().getHub();
        OATable table = new OATable(hubTable) {
            @Override
            public void customizeRenderer(JLabel lbl, JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column, boolean wasChanged, boolean wasMouseOver) {
            }
            @Override
            public String getToolTipText(int row, int col, String defaultValue) {
                defaultValue = super.getToolTipText(row, col, defaultValue);
                return defaultValue;
            }
            @Override
            public void onDoubleClick() {
                if (ReportClassJfcBase.this.getModel().getAllowGotoEdit()) {
                    ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                }
            }
        };
     
        // table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table.setAllowDnD(false);
        table.setAllowSorting(getModel().getAllowTableSorting());
        if (getModel().getAllowTableFilter()) {
            table.setMasterFilterHub(getModel().getHub());
        }
        // table.setColumnProperties(ModelDelegate.getProperties(), "ReportClass");
    
        table.addCounterColumn();
        if (getModel().getAllowMultiSelect()) {
            table.addSelectionColumn(getModel().getMultiSelectHub(), "Select", 6);
        }
        createReadOnlyTableColumns(table);
        
        table.resizeColumnsToFitHeading();
        table.setPreferredSize(3, 2, true);
        table.setComponentPopupMenu(createTablePopupMenu());
        return table;
    }
    
    protected void createReadOnlyTableColumns(OATable table) {
        OALabel lbl;
        OATableColumn tc;
        lbl = new OALabel(getHub(), ReportClass.P_Name, 18);
        tc = table.addColumn("Name", 18, lbl);
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(ReportClass.P_Name));
        }
        lbl = new OALabel(getHub(), ReportClass.P_ClassName, 18);
        tc = table.addColumn("Class Name", 18, lbl);
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(ReportClass.P_ClassName));
        }
        lbl = new OALabel(getHub(), OAString.cpp(ReportClass.P_ReportDefs, ReportDef.P_Name));
        tc = table.addColumn("Report Defs", 34, lbl);
    }
    
    public OAButton createGotoEditButton() {
        if (!getModel().getAllowGotoEdit()) return null;
        OAButton cmd = new OAButton(getHub(), "Details ...", Resource.getJarIcon(Resource.IMG_Goto), OAButton.GOTO) {
            @Override
            public void afterActionPerformed() {
                ReportClassJfcBase.this.getEditDialog(this).setVisible(true);
                super.afterActionPerformed();
            }
        };
        cmd.setToolTipText("go to the selected "+getModel().getDisplayName());
        OAButton.setup(cmd);
        return cmd;
    }
    
    public OAButton createAddButton() {
        if (!getModel().getAllowAdd()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.ADD_MANUAL) {
            @Override
            public boolean onActionPerformed() throws Exception {
                ReportClassJfcBase.this.onAdd();
                return true;
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Add ...");
        OAButton.setup(cmd);
        return cmd;
    }
    public OAButton createNewButton() {
        if (!getModel().getAllowNew()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.NEW) {
            public void afterActionPerformed() {
                ReportClassJfcBase.this.onNewReportClassCreated();
                super.afterActionPerformed();
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("New");
        cmd.setup();
        cmd.setToolTipText("Create new "+getModel().getDisplayName());
        return cmd;
    }
    public OAButton createInsertButton() {
        if (!getModel().getAllowNew() || !getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.INSERT) {
            public void afterActionPerformed() {
                ReportClassJfcBase.this.onNewReportClassCreated();
                super.afterActionPerformed();
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Insert");
        cmd.setup();
        cmd.setToolTipText("Insert a new "+getModel().getDisplayName());
        return cmd;
    }
    public OAButton createSaveButton() {
        if (!getModel().getAllowSave()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.SAVE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Save");
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setup();
        cmd.setToolTipText("Save "+getModel().getDisplayName());
        return cmd;
    }
    
    public OAButton createRemoveButton() {
        if (!getModel().getAllowRemove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.REMOVE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setText("Remove");
        cmd.setup();
        cmd.setToolTipText("Remove "+getModel().getDisplayName()+" from this list");
        return cmd;
    }
    public OAButton createDeleteButton() {
        if (!getModel().getAllowDelete()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.DELETE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setConfirmMessage("OK to Delete this "+getModel().getDisplayName()+" from system?");
        cmd.setText("Delete ...");
        cmd.setup();
        cmd.setUseSwingWorker(true);
        cmd.setProcessingText("Processing ...", "Please wait while deleting "+getModel().getDisplayName());
        cmd.setToolTipText("Delete "+getModel().getDisplayName());
        return cmd;
    }
    
    public OAButton createRefreshButton() {
        if (!getModel().getAllowRefresh()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.REFRESH);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Refresh");
        cmd.setup();
        cmd.setToolTipText("Refresh "+getModel().getDisplayName()+" from DataSource");
        return cmd;
    }
    
    public OAButton createMoveUpButton() {
        if (!getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.UP);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setup();
        cmd.setToolTipText("Move current "+getModel().getDisplayName()+" up in the list");
        return cmd;
    }
    public OAButton createMoveDownButton() {
        if (!getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.DOWN);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setup();
        cmd.setToolTipText("Move current "+getModel().getDisplayName()+" down in the list");
        return cmd;
    }
    
    public JToolBar createToolBar(final ToolBarOptions tbo) {
        JToolBar toolBar = new JToolBar();
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.add(Box.createHorizontalStrut(10));
        updateToolBar(toolBar, tbo);
        toolBar.add(Box.createHorizontalGlue());
        return toolBar;
    }
    // main createToolBar
    public void updateToolBar(final JToolBar toolBar, final ToolBarOptions tbo) {
        JButton jcmd;
        OAButton cmd;
        
        if (tbo.bGoBack) {
            jcmd = createGotoListButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(7));
            }
        }
        if (tbo.bIcon) {
            Icon icon = getTitleIcon();
            JLabel lbl = new JLabel(getModel().getPluralDisplayName(), icon, JLabel.LEFT);
            lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
            toolBar.add(lbl);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bLabel) {
            OALabel lbl = new OALabel(getHub(), OAString.cpp(ReportClass.P_Name));
            lbl.setToolTipTextPropertyPath(OAString.cpp(ReportClass.P_Name));
            lbl.setMaxCols(20);
            lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
            lbl.setBorder(new CustomLineBorder(0,0,0,1,Color.gray));
            toolBar.add(lbl);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bGoto) {
            cmd = createGotoEditButton();
            if (cmd != null) {
                toolBar.add(cmd);
                if (!tbo.bCommands) toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bCommands) {
            cmd = createMoveUpButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createMoveDownButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createSaveButton();
            if (cmd != null) toolBar.add(cmd);
            
            cmd = createAddButton();
            if (cmd != null) toolBar.add(cmd);
            
            cmd = createNewButton();
            if (cmd != null) {
                cmd.setFocusComponent(tableDtTxtCreated);
                toolBar.add(cmd);
            }
            cmd = createInsertButton();
            if (cmd != null) {
                cmd.setFocusComponent(tableDtTxtCreated);
                toolBar.add(cmd);
            }
            cmd = createRemoveButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createDeleteButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createRefreshButton();
            if (cmd != null) toolBar.add(cmd);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bSearch) {
            jcmd = createSearchButton();
            if (jcmd == null) tbo.bSearch = false;
            else {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bFind) {
            OAAutoCompleteTextField txt = createAutoCompleteTextField();
            if (txt != null) {
                toolBar.add(Box.createHorizontalStrut(6));
                JLabel lbl = new JLabel(Resource.getJarIcon("find16.png"));
                lbl.setText("Find:");
                lbl.setToolTipText("Search using Name");
                OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), lbl);
                toolBar.add(lbl);
                toolBar.add(Box.createHorizontalStrut(5));
                toolBar.add(new OAResizePanel(txt));
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (!tbo.bSearch && tbo.bHubSearch) {
            jcmd = createHubSearchButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bCustom) {
            addCustomCommands(toolBar);
        }
        
        if (tbo.bDownload) {
            jcmd = createDownloadButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
    
    }
    public void addCustomCommands(JToolBar toolBar) {
        if (toolBar == null) return;
    }
    public JButton createGoBackButton() {
        return null;
    }
    public JButton createGotoListButton() {
        if (!getModel().getAllowGotoList()) return null;
        JButton cmd = new JButton();
        cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_GoBack)));
        cmd.setText("Listing");
        cmd.setToolTipText("Go to listing");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ReportClassJfcBase.this.showCardPanel(ReportClassJfcBase.this.CARD_List);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public OAButton createSearchButton() {
        return createSearchButton(false);
    }
    
    public OAButton createSearchButton(boolean bForSuperUser) {
        boolean bAllow = getModel().getAllowSearch();
        if (!bAllow && !bForSuperUser) return null;
        OAButton cmd = new OAButton(getHub(), getModel().getDisplayName() + " search ...", Resource.getJarIcon("search.gif"), OAButton.SEARCH) {
            @Override
            public Object getSearchObject() {
                ReportClass reportClass = ReportClassJfcBase.this.onSearch();
                return reportClass;
            }
            @Override
            public void afterActionPerformed() {
                super.afterActionPerformed();
                OATree tree = getTreeUsed();
                if (tree != null) {
                    tree.setSelectedNode(getHub().getAO());
                }
                onShowEditPanel();
            }
        };
        if (!bAllow) {
            cmd.getController().getVisibleChangeListener().addOnlySuperAdmin(getHub());
        }
        return cmd;
    }
    
    public JButton createHubSearchButton() {
        if (!getModel().getAllowHubSearch()) return null;
        OAButton cmd = new OAButton(getHub(), "Search ...", Resource.getJarIcon("hubsearch16.png"), OAButton.HUBSEARCH) {
            @Override
            public void afterActionPerformed() {
                ReportClassJfcBase.this.onHubSearch();
                super.afterActionPerformed();
            }
        };
        cmd.setToolTipText("table search");
        return cmd;
    }
    public JButton createDownloadButton() {
        if (!getModel().getAllowDownload()) return null;
        JButton cmd = new JButton("Download ...");
        cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_Download)));
        cmd.setToolTipText("download data to csv file");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ReportClassJfcBase.this.onDownload();
            }
        });
        OAJfcController jc = OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), cmd);
        OAButton.setup(cmd);
        return cmd;
    }
    protected void onDownload() {
        DownloadDialog dd = new DownloadDialog<ReportClass>(getHub());
        addDownloadProperties(dd);
        dd.download();
    }
    protected void addDownloadProperties(DownloadDialog dd) {
        dd.addProperty("Id", ReportClass.P_Id);
        dd.addProperty("name", ReportClass.P_Name);
        dd.addProperty("className", ReportClass.P_ClassName);
        dd.addProperty("reportDefs.id", ReportClassPP.reportDefs().id());
        dd.addProperty("reportDefs.name", ReportClassPP.reportDefs().name());
    }
    // Card Panel
    public JPanel getCardPanel() {
        if (cardPanel != null) return cardPanel;
        cardLayout = new CardLayout(5,5) {
            JPanel panList;
            JPanel panEdit;
            @Override
            public void show(Container parent, String name) {
                if (CARD_List.equals(name)) {
                    if (panList == null) {
                        panList = createListCardPanel();
                        cardPanel.add(panList, CARD_List);
                    }
                }
                else if (CARD_Edit.equals(name)) {
                    if (panEdit == null) {
                        panEdit = createEditCardPanel();
                        cardPanel.add(panEdit, CARD_Edit);
                    }
                }
                super.show(parent, name);
            }
        };
        cardPanel = new JPanel(cardLayout);
        
        cardPanel.add(new JLabel("loading ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_Edit);
        
        cardLayout.show(cardPanel, CARD_List);
        return cardPanel;
    }
    public JPanel createListCardPanel() {
        JPanel pan = createTablePanel();
        return pan;
    }
    public JPanel createEditOnePanel() {
        return createEditOnePanel(null);
    }
    public JPanel createEditOnePanel(JTabbedPane tp) {
        JPanel pan = new JPanel(new BorderLayout());
        if (tp == null) {
            if (this.tabbedPane == null) tp = getTabbedPane();
            else tp = createTabbedPane();
        }
        pan.add(createEditPanel(tp, true), BorderLayout.CENTER);
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createOneToolBar())), BorderLayout.NORTH);
        // cardPanel.add(getReportDefsJfc().getCardPanel(), CARD_ReportDefs); // this will be created when needed by showCardPanel(..)
        return pan;
    }
    
    public JPanel createEditCardPanel() {
        return createEditCardPanel(null);
    }
    
    public JPanel createEditCardPanel(JTabbedPane tp) {
        JPanel pan = new JPanel(new BorderLayout());
        if (tp == null) {
            if (this.tabbedPane == null) tp = getTabbedPane();
            else tp = createTabbedPane();
        }
        pan.add(createEditPanel(tp, true), BorderLayout.CENTER);
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createEditPanelToolBar())), BorderLayout.NORTH);
        // cardPanel.add(getReportDefsJfc().getCardPanel(), CARD_ReportDefs); // this will be created when needed by showCardPanel(..)
        return pan;
    }
    public CardLayout getCardLayout() {
        if (cardLayout == null) {
            cardLayout = new CardLayout(5,5);
        }
        return cardLayout;
    }
    
    // Edit Panel
    public JPanel createEditPanel() {
        return createEditPanel(null, true);
    }
    public JPanel createEditPanel(JTabbedPane tabbedPane, final boolean bUseCombinedDetail) {
        if (tabbedPane == null) {
            if (this.tabbedPane == null) tabbedPane = getTabbedPane();
            else tabbedPane = createTabbedPane();
        }
        else if (this.tabbedPane == null) this.tabbedPane = tabbedPane;
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(2, 2, 2, 2);
        gc.anchor = gc.WEST;
        JPanel panel;
        JLabel lbl;
        JToolBar toolBar;
        OALabel olbl;
        JButton cmd;
        JComponent comp;
        OAJfcController jfcController;
        OADateTimeTextField dttxt;
        OATextField txt;
        JPanel pan;
        JPanel panMain = new JPanel(new BorderLayout());
        panel = new JPanel(new GridBagLayout());
        panel.setBorder(new EmptyBorder(5,5, 3,3));
    
        lbl = new JLabel("Created:");
        gc.anchor = gc.WEST;
        panel.add(lbl, gc);
        gc.anchor = gc.NORTHWEST;
        dttxt = createCreatedDateTimeTextField();
        if (getModel().getViewOnly()) dttxt.getController().setViewOnly(true);
        dttxt.setLabel(lbl);
        dttxtCreated = dttxt;
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        comp = new OAResizePanel(dttxt, 95);
        panel.add(comp, gc);
        gc.fill = gc.NONE;
        gc.gridwidth = 1;
    
        lbl = new JLabel("Name:");
        gc.anchor = gc.WEST;
        panel.add(lbl, gc);
        gc.anchor = gc.NORTHWEST;
        txt = createNameTextField();
        if (getModel().getViewOnly()) txt.getController().setViewOnly(true);
        txt.setLabel(lbl);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        comp = new OAResizePanel(txt, 95);
        panel.add(comp, gc);
        gc.fill = gc.NONE;
        gc.gridwidth = 1;
    
        lbl = new JLabel("Class Name:");
        gc.anchor = gc.WEST;
        panel.add(lbl, gc);
        gc.anchor = gc.NORTHWEST;
        txt = createClassNameTextField();
        if (getModel().getViewOnly()) txt.getController().setViewOnly(true);
        txt.setLabel(lbl);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        comp = new OAResizePanel(txt, 95);
        panel.add(comp, gc);
        gc.fill = gc.NONE;
        gc.gridwidth = 1;
    
        // take up remaining space
        lbl = new JLabel("");
        panel.add(lbl, gc);
        gc.gridwidth = gc.REMAINDER;
        gc.weightx = gc.weighty = 1.0f;
        gc.fill = gc.BOTH;
        panel.add(lbl, gc);
        gc.gridwidth = 1;
        gc.weightx = gc.weighty = 0.0f;
        gc.fill = gc.NONE;
    
        tabbedPane.addTab(getModel().getDisplayName(), getIcon(), new JScrollPane(panel), null);
        panMain.add(tabbedPane, BorderLayout.CENTER);
    
        Icon icon;
        icon = Resource.getJarIcon("reportDef.gif");
        icon = new ScaledImageIcon(icon, 32, 20);
        tabbedPane.addChangeListener(new ChangeListener() {
            volatile JPanel panThis;
            volatile Exception ex;
            @Override
            public void stateChanged(ChangeEvent e) {
                if (panThis != null) return;
                if (ReportClassJfcBase.this.TAB_ReportDefs == 0) return;
                final JTabbedPane tp = (JTabbedPane) e.getSource();
                if (tp.getSelectedIndex() != ReportClassJfcBase.this.TAB_ReportDefs) return;
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            if (bUseCombinedDetail) panThis = getReportDefsJfc().createCombinedPanel();
                            else panThis = getReportDefsJfc().createTablePanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating UI for ReportClass", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panThis == null) panThis = new JPanel();
                        tp.setComponentAt(ReportClassJfcBase.this.TAB_ReportDefs, panThis);
                    }
                };
                sw.execute();
            }
        });
        if (getModel().getReportDefsModel().getCreateUI()) {
            if ((this.TAB_ReportDefs = tabbedPane.getTabCount()) == 0) {
                JPanel panThis;
                if (bUseCombinedDetail) panThis = getReportDefsJfc().createCombinedPanel();
                else panThis = getReportDefsJfc().createTablePanel();
                tabbedPane.setComponentAt(ReportClassJfcBase.this.TAB_ReportDefs, panThis);
            }
            else {
                tabbedPane.addTab("Report Defs", icon, new JLabel("loading ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), "Report Defs");
            }
        }
        panel = panMain;
        return panel;
    }
    
    public JTabbedPane getTabbedPane() {
        if (tabbedPane == null) {
            tabbedPane = createTabbedPane();
        }
        return tabbedPane;
    }
    public JTabbedPane createTabbedPane() {
        JTabbedPane tabbedPane = new JTabbedPane();
        new TabbedPaneController(getHub(), tabbedPane);
        tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT); // WRAP_TAB_LAYOUT
        tabbedPane.setFocusable(true);
        return tabbedPane;
    }
    
    // edit dialog
    public JDialog getEditDialog(Component comp) {
        JDialog dlgEdit;
        if (wrEditDialog != null) {
            dlgEdit = wrEditDialog.get();
            if (dlgEdit != null) return dlgEdit;
        }
        if (jfcReportDefs != null) {
            // need to create a new Jfc for dialog
            ReportClassJfc jfc = new ReportClassJfc(getModel());
            dlgEdit = jfc.getEditDialog(comp);
            wrEditDialog = new WeakReference(dlgEdit);
            return dlgEdit;
        }
        Window win = JfcDelegate.getWindow(comp);
        if (win == null) win = OAJfcUtil.getMainWindow();
        dlgEdit = new JDialog(win, getModel().getDisplayName(), ModalityType.MODELESS) {
            @Override
            public void setVisible(boolean b) {
                super.setVisible(b);
                if (b) super.repaint();
            }
        };
        wrEditDialog = new WeakReference(dlgEdit);
        dlgEdit.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        dlgEdit.setLayout(new BorderLayout());
        JToolBar tb = createToolBar(ToolBarOptions.createDialogToolBar());
        if (tb != null) {
            dlgEdit.add(new OAScroller(tb), BorderLayout.NORTH);
        }
        ReportClassJfc jfc = new ReportClassJfc(getModel());
        JPanel panEdit = jfc.createEditPanel();
        dlgEdit.add(panEdit, BorderLayout.CENTER);
        
        panEdit.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false), "esc");
        panEdit.getActionMap().put("esc", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                getEditDialog(null).setVisible(false);
            }
        });
        
        OAJfcUtil.pack(dlgEdit);
        Dimension dimMax;
        if (win != null) {
            dimMax = win.getSize();
        }
        else {
            dimMax = Toolkit.getDefaultToolkit().getScreenSize();
        }
        Dimension dim = dlgEdit.getSize();
        dim.width *= 1.25;
        dim.height *= 1.25;
        dim.width = (int) Math.min(dim.width, dimMax.width);
        dim.height = (int) Math.min(dim.height, dimMax.height);
        dimMax.width *= .75;
        dimMax.height *= .75;
        dim.width = (int) Math.max(dim.width, dimMax.width);
        dim.height = (int) Math.max(dim.height, dimMax.height);
        dlgEdit.setSize(dim);
        
        if (win != null) dlgEdit.setLocationRelativeTo(win);
        return dlgEdit;
    }
    
    
    public OALabel createIdLabel() {
        OALabel lbl = new OALabel(getHub(), ReportClass.P_Id, 6);
        lbl.setMaximumColumns(8);
        return lbl;
    }
    
    public OADateTimeTextField createCreatedDateTimeTextField() {
        OADateTimeTextField dttxt = new OADateTimeTextField(getHub(), ReportClass.P_Created, 15);
        dttxt.setMinimumColumns(0);
        dttxt.setMaximumColumns(22);
        // setup(dttxt);
        return dttxt;
    }
    
    public OATextField createNameTextField() {
        OATextField txt = new OATextField(getHub(), ReportClass.P_Name, 18);
        txt.setMinimumColumns(0);
        txt.setMaximumColumns(55);
        // setup(txt);
        return txt;
    }
    
    public OATextField createClassNameTextField() {
        OATextField txt = new OATextField(getHub(), ReportClass.P_ClassName, 18);
        txt.setMinimumColumns(0);
        txt.setMaximumColumns(75);
        // setup(txt);
        return txt;
    }
    
    protected void setup(JTextComponent txt) {
        OATextController tc = new OATextController(txt, Resource.getSpellChecker(), true);
        String s = txt.getToolTipText();
        if (!OAString.isEmpty(s)) s = "<html>"+s+"<br>";
        else s = "<html>";
        s += "<small><i>Right click for more options";
        txt.setToolTipText(s);
    }
    
    // Autocomplete
    public OAAutoCompleteTextField createAutoCompleteTextField() {
        return createAutoCompleteTextField(PP_Display);
    }
    public OAAutoCompleteTextField createAutoCompleteTextField(String propertyPath) {
        OAAutoCompleteTextField txt = new OAAutoCompleteTextField(getHub(), propertyPath, 18);
        txt.setMaximumColumns(55);
        txt.setToolTipText("Search using Name");
        return txt;
    }
    
    
    public ReportDefJfc getReportDefsJfc() {
        if (jfcReportDefs == null) {
            jfcReportDefs = createReportDefsJfc();
        }
        return jfcReportDefs;
    }
    public ReportDefJfc createReportDefsJfc() {
        return createReportDefsJfc(true);
    }
    public ReportDefJfc createReportDefsJfc(final boolean bIsEmbedded) {
        jfcReportDefs = new ReportDefJfc(getModel().getReportDefsModel()) {
            @Override
            public JPanel getCardPanel() {
                if (cardPanel != null) return cardPanel;
                if (!bIsEmbedded) return super.getCardPanel();
                cardPanel = new JPanel(getCardLayout());
                JPanel pan = new JPanel(new BorderLayout());
                pan.add(createToolBar(ToolBarOptions.createEditPanelToolBar()), BorderLayout.NORTH);
                pan.add(createEditPanel(), BorderLayout.CENTER);
                cardPanel.add(pan, CARD_Edit);
                return cardPanel;
            }
    
            @Override
            public void showCardPanel(String name) {
                if (!bIsEmbedded) {
                    super.showCardPanel(name);
                    ReportClassJfcBase.this.showCardPanel(name);
                    return;
                }
                if (name.equals(ReportDefJfc.CARD_List)) {
                    ReportClassJfcBase.this.showCardPanel(CARD_Edit);
                    if (ReportClassJfcBase.this.TAB_ReportDefs >= 0) {
                        ReportClassJfcBase.this.getTabbedPane().setSelectedIndex(ReportClassJfcBase.this.TAB_ReportDefs);
                    }
                }
                else if (name.equals(ReportDefJfcBase.CARD_Edit)) {
                    ReportClassJfcBase.this.showCardPanel(CARD_Edit);
                    if (ReportClassJfcBase.this.TAB_ReportDefs >= 0) {
                        ReportClassJfcBase.this.getTabbedPane().setSelectedIndex(ReportClassJfcBase.this.TAB_ReportDefs);
                    }
                }
                else {
                    ReportClassJfcBase.this.showCardPanel(CARD_ReportDefs);
                    super.showCardPanel(name);
                }
            }
            public JButton createGoBackButton() {
                JButton cmd = new JButton();
                cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_GoBack)));
                cmd.setToolTipText("Go to " + ReportClassJfcBase.this.getModel().getDisplayName());
                cmd.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        ReportClassJfcBase.this.showCardPanel(ReportClassJfcBase.this.CARD_Edit);
                        ReportClassJfcBase.this.getHub().resetAO(); // this will set selected treeNode
                    }
                });
                OAButton.setup(cmd);
                return cmd;
            }
        };
        jfcReportDefs.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcReportDefs, this);
        return jfcReportDefs;
    }
    // OnShowCommands
    public void showCardPanel(String name) {
        if (name == null) return;
        if (cardPanel == null) return;
        if (name.equalsIgnoreCase(CARD_ReportDefs)) {
            if ( !OAArray.contains(cardPanel.getComponents(), getReportDefsJfc().getCardPanel()) ) {
                cardPanel.add(getReportDefsJfc().getCardPanel(), CARD_ReportDefs);
            }
        }
        getCardLayout().show(getCardPanel(), name);
    }
    protected void onShowListPanel() {
        showCardPanel(CARD_List);
    }
    protected void onShowEditPanel() {
        showCardPanel(CARD_Edit);
    }
    protected void onNewReportClassCreated() {
        onShowEditPanel();
        if (getTabbedPane().getTabCount() > 0) {
            getTabbedPane().setSelectedIndex(0);
        }
    }
    protected void onDoubleClickTreeNode() {
        if (getModel().getAllowGotoEdit()) {
            getEditDialog(null).setVisible(true);
        }
    }
    
    // Inner Search
    public ReportClassSearchJfc getSearchHubJfc() {
        if (jfcSearchHub != null) return jfcSearchHub;
        ReportClassSearchModel modelSearch = new ReportClassSearchModel();
        modelSearch.setSearchFromHub(getHub());
        jfcSearchHub = new ReportClassSearchJfc(modelSearch, true, getModel().getAllowMultiSelect()) {
            @Override
            public JPanel createSearchFromPanel() {
                return null;
            }
            @Override
            public JPanel createSearchTreePanel() {
                return null;
            }
        };
        return jfcSearchHub;
    }
    protected void onHubSearch() {
        getSearchHubJfc().getDialog().setVisible(true);
        if (!getSearchHubJfc().wasSelected()) return;
        if (getModel().getAllowMultiSelect()) {
            getModel().getMultiSelectHub().clear();
            for (ReportClass reportClass : getSearchHubJfc().getModel().getMultiSelectHub()) {
                if (getHub().contains(reportClass)) {
                    getModel().getMultiSelectHub().add(reportClass);
                }
            }
            getHub().setAO(getModel().getMultiSelectHub().getAt(0));
        }
        else {
            ReportClass reportClass = getSearchHubJfc().getSelected();
            if (reportClass != null) {
                if (getHub().contains(reportClass)) {
                    getHub().setAO(reportClass);
                }
            }
        }
    }
    // Search
    protected ReportClassSearchJfc getSearchJfc() {
        if (jfcSearch == null) {
            jfcSearch = new ReportClassSearchJfc();
        }
        return jfcSearch;
    }
    protected ReportClass onSearch() {
        getSearchJfc().getModel().beforeInput();
        getSearchJfc().getDialog().setVisible(true);
        ReportClass reportClass = null;
        if (getSearchJfc().wasSelected()) reportClass = getSearchJfc().getSelected();
        return reportClass;
    }
    // Add
    protected ReportClassSearchJfc getAddJfc() {
        if (jfcAdd == null) {
            jfcAdd = new ReportClassSearchJfc();
        }
        return jfcAdd;
    }
    protected void onAdd() {
        getAddJfc().getDialog().setVisible(true);
        if (!getAddJfc().wasSelected()) return;
        ReportClass reportClass = getAddJfc().getSelected();
        if (reportClass == null) return;
        getHub().add(reportClass);
        getHub().setAO(reportClass);
    }
    
    
    public static void main(String[] args) {
        AppUser user = new AppUser();
        user.setAdmin(true);
        user.setEditProcessed(true);
        AppUserLogin userLogin = new AppUserLogin();
        userLogin.setAppUser(user);
        ModelDelegate.setLocalAppUserLogin(userLogin);
        TestDelegate td = new TestDelegate();
        td.createSampleData(null);
        
        com.viaoa.context.OAContext.setContextHub(null, ModelDelegate.getLocalAppUserHub());
        ReportClassJfc ui = new ReportClassJfc(ModelDelegate.getReportClasses().createSharedHub()) {
            @Override
            protected ReportClassSearchJfc getSearchJfc() {
                if (this.jfcSearch == null) {
                    this.jfcSearch = new ReportClassSearchJfc(false) {
                        @Override
                        protected void onSearch(JComponent comp) {
                            super.onSearch(comp);
                            afterSearchCustom();
                        }
                    };
                }
                return this.jfcSearch;
            }
            private void afterSearchCustom() {
                getModel().getOriginalHub().setSharedHub(getSearchJfc().getModel().getHub());
            }
        };
        ui.getModel().setAllowNew(true);
        ui.getModel().setAllowDelete(true);
        
        JFrame frm = new JFrame();
        JfcDelegate.setMainWindow(frm);
        frm.setTitle(ui.getModel().getDisplayName());
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu(ui.getModel().getPluralDisplayName());
        menu.add(ui.createNewMenuItem());
        menu.add(ui.createSaveMenuItem());
        menu.addSeparator();
        menu.add(ui.createDeleteMenuItem());
        menuBar.add(menu);
        
        frm.setJMenuBar(menuBar);
        
        OATree tree = new OATree(15, 17);
        tree.setAllowDnD(true);
        
        OATreeNode tn = ui.getTreeTitleNode();
        tree.add(tn);
        tn.add(ui.getTreeNode());
        
        String cmd = "esc";
        tree.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0 ,false), cmd);
        tree.getActionMap().put(cmd, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        
        frm.setLayout(new BorderLayout());
        
        // ui.getTablePanel().add(new OAScroller(ui.createToolBar(true)), BorderLayout.NORTH);
        // frm.add(ui.getTablePanel(), BorderLayout.SOUTH);
        
        JPanel pan = new JPanel(new BorderLayout());
        // pan.add(ui.createTitlePanel(), BorderLayout.NORTH);
        pan.add(ui.getCardPanel());
        
        JToolBar toolBar = ui.createToolBar(ToolBarOptions.createNorthTableSearchToolBar());
        if (toolBar != null) frm.add(new OAScroller(toolBar), BorderLayout.NORTH);
        
        toolBar = new JToolBar();
        toolBar.add(Box.createHorizontalStrut(25));
        AppUserJfc jfcAU = new AppUserJfc(ModelDelegate.getLocalAppUserHub());
        OACheckBox chk = jfcAU.createEditProcessedCheckBox();
        chk.setText("Edit Processed");
        toolBar.add(chk);
        chk = jfcAU.createAdminCheckBox();
        chk.setText("Is Admin");
        toolBar.add(chk);
        JPanel panx = new JPanel(new BorderLayout());
        panx.add(toolBar, BorderLayout.NORTH);
        
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.add("Main", pan);
        
        pan = new JPanel(new GridBagLayout());
        pan.setBorder(new EmptyBorder(20,20,10,10));
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(2, 2, 2, 2);
        gc.anchor = gc.WEST;
        pan.add(new JLabel("Label: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        pan.add(new OAResizePanel(ui.createLabel(), 75), gc);
        gc.gridwidth = 1;
        gc.fill = gc.NONE;
        pan.add(new JLabel("Combo: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        pan.add(new OAResizePanel(ui.createComboBox(), 75), gc);
        gc.gridwidth = 1;
        gc.fill = gc.NONE;
        pan.add(new JLabel("Table Combo: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        pan.add(new OAResizePanel(ui.createTableComboBox(), 75), gc);
        gc.gridwidth = 1;
        gc.fill = gc.NONE;
        pan.add(new JLabel("List: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.BOTH;
        gc.weightx = gc.weighty = 1.0;
        pan.add(new OAResizePanel(new JScrollPane(ui.createList()), 75, true), gc);
        pan.add(new JLabel(), gc);
        panx.add(new JScrollPane(pan), BorderLayout.CENTER);
        tabbedPane.add("Sample", panx);
        JSplitPane sp = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, new JScrollPane(tree), tabbedPane);
        sp.setOneTouchExpandable(true);
        sp.setDividerSize(6);
    
        /*
        sp = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, sp, new JScrollPane(ui.createList()));
        sp.setOneTouchExpandable(true);
        sp.setDividerSize(6);
        sp.setResizeWeight(.90);
        */
        frm.add(sp, BorderLayout.CENTER);
        
        OAJfcUtil.pack(frm);
        Dimension d = frm.getSize();
        Dimension dimScreen = Toolkit.getDefaultToolkit().getScreenSize();
        d.width = Math.min(d.width, dimScreen.width - 80);
        d.height = Math.min(d.height, dimScreen.height - 80);
        frm.setSize(d);
        
        frm.setLocation(new Point(40, 40));
        frm.setVisible(true);
    }
}

