// Generated by OABuilder 09/14/24 04:16 PM

package com.template.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.template.model.*;
import com.template.model.oa.*;
import com.template.model.oa.propertypath.*;
import com.template.delegate.*;
import com.template.delegate.oa.*;
import com.template.resource.Resource;
import com.template.view.*;

public class ReportDefJfc extends ReportDefJfcBase {
    
    public ReportDefJfc() {
    }
    
    public ReportDefJfc(Hub<ReportDef> hubReportDef) {
        super(hubReportDef);
    }
    
    public ReportDefJfc(ReportDefModel modelReportDef) {
        super(modelReportDef);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

