// Generated by OABuilder
package com.template.model.oa;
 
import java.util.logging.*;
import java.sql.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.annotation.*;
import com.template.delegate.oa.*;
import com.template.model.oa.filter.*;
import com.template.model.oa.propertypath.*;
import com.viaoa.util.OADateTime;
import com.viaoa.util.OADate;
 
@OAClass(
    shortName = "aue",
    displayName = "App User Error",
    isProcessed = true,
    displayProperty = "dateTime"
)
@OATable(
    indexes = {
        @OAIndex(name = "AppUserErrorAppUserLogin", fkey = true, columns = { @OAIndexColumn(name = "AppUserLoginId") })
    }
)
public class AppUserError extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(AppUserError.class.getName());

    public static final String PROPERTY_Id = "Id";
    public static final String P_Id = "Id";
    public static final String PROPERTY_DateTime = "DateTime";
    public static final String P_DateTime = "DateTime";
    public static final String PROPERTY_Message = "Message";
    public static final String P_Message = "Message";
    public static final String PROPERTY_StackTrace = "StackTrace";
    public static final String P_StackTrace = "StackTrace";
    public static final String PROPERTY_Reviewed = "Reviewed";
    public static final String P_Reviewed = "Reviewed";
    public static final String PROPERTY_ReviewNote = "ReviewNote";
    public static final String P_ReviewNote = "ReviewNote";
     
     
    public static final String PROPERTY_AppUserLogin = "AppUserLogin";
    public static final String P_AppUserLogin = "AppUserLogin";
     
    protected volatile int id;
    protected volatile OADateTime dateTime;
    protected volatile String message;
    protected volatile String stackTrace;
    protected volatile OADate reviewed;
    protected volatile String reviewNote;
     
    // Links to other objects.
    protected volatile transient AppUserLogin appUserLogin;
     
    public AppUserError() {
    }
     
    public AppUserError(int id) {
        this();
        setId(id);
    }
     

    @OAProperty(isUnique = true, displayLength = 5)
    @OAId()
    @OAColumn(sqlType = java.sql.Types.INTEGER)
    public int getId() {
        return id;
    }
    public void setId(int newValue) {
        int old = id;
        fireBeforePropertyChange(P_Id, old, newValue);
        this.id = newValue;
        firePropertyChange(P_Id, old, this.id);
    }
     
    @OAProperty(displayName = "Date TIme", displayLength = 15)
    @OAColumn(name = "DateTimeValue", sqlType = java.sql.Types.TIMESTAMP)
    public OADateTime getDateTime() {
        return dateTime;
    }
    public void setDateTime(OADateTime newValue) {
        OADateTime old = dateTime;
        fireBeforePropertyChange(P_DateTime, old, newValue);
        this.dateTime = newValue;
        firePropertyChange(P_DateTime, old, this.dateTime);
    }
     
    @OAProperty(maxLength = 250, displayLength = 35, columnLength = 25)
    @OAColumn(maxLength = 250)
    public String getMessage() {
        return message;
    }
    public void setMessage(String newValue) {
        String old = message;
        fireBeforePropertyChange(P_Message, old, newValue);
        this.message = newValue;
        firePropertyChange(P_Message, old, this.message);
    }
     
    @OAProperty(displayName = "Stack Trace", maxLength = 250, displayLength = 40, columnLength = 25)
    @OAColumn(sqlType = java.sql.Types.CLOB)
    public String getStackTrace() {
        return stackTrace;
    }
    public void setStackTrace(String newValue) {
        String old = stackTrace;
        fireBeforePropertyChange(P_StackTrace, old, newValue);
        this.stackTrace = newValue;
        firePropertyChange(P_StackTrace, old, this.stackTrace);
    }
     
    @OAProperty(displayLength = 8, isProcessed = true)
    @OAColumn(sqlType = java.sql.Types.DATE)
    public OADate getReviewed() {
        return reviewed;
    }
    public void setReviewed(OADate newValue) {
        OADate old = reviewed;
        fireBeforePropertyChange(P_Reviewed, old, newValue);
        this.reviewed = newValue;
        firePropertyChange(P_Reviewed, old, this.reviewed);
    }
     
    @OAProperty(displayName = "Review Note", maxLength = 254, displayLength = 40, isProcessed = true)
    @OAColumn(maxLength = 254)
    public String getReviewNote() {
        return reviewNote;
    }
    public void setReviewNote(String newValue) {
        String old = reviewNote;
        fireBeforePropertyChange(P_ReviewNote, old, newValue);
        this.reviewNote = newValue;
        firePropertyChange(P_ReviewNote, old, this.reviewNote);
    }
     
    @OAOne(
        displayName = "App User Login", 
        reverseName = AppUserLogin.P_AppUserErrors, 
        required = true, 
        allowCreateNew = false
    )
    @OAFkey(columns = {"AppUserLoginId"})
    public AppUserLogin getAppUserLogin() {
        if (appUserLogin == null) {
            appUserLogin = (AppUserLogin) getObject(P_AppUserLogin);
        }
        return appUserLogin;
    }
    public void setAppUserLogin(AppUserLogin newValue) {
        AppUserLogin old = this.appUserLogin;
        fireBeforePropertyChange(P_AppUserLogin, old, newValue);
        this.appUserLogin = newValue;
        firePropertyChange(P_AppUserLogin, old, this.appUserLogin);
    }
     
    public void load(ResultSet rs, int id) throws SQLException {
        this.id = id;
        java.sql.Timestamp timestamp;
        timestamp = rs.getTimestamp(2);
        if (timestamp != null) this.dateTime = new OADateTime(timestamp);
        this.message = rs.getString(3);
        this.stackTrace = rs.getString(4);
        java.sql.Date date;
        date = rs.getDate(5);
        if (date != null) this.reviewed = new OADate(date);
        this.reviewNote = rs.getString(6);
        int appUserLoginFkey = rs.getInt(7);
        if (!rs.wasNull() && appUserLoginFkey > 0) {
            setProperty(P_AppUserLogin, new OAObjectKey(appUserLoginFkey));
        }
        if (rs.getMetaData().getColumnCount() != 7) {
            throw new SQLException("invalid number of columns for load method");
        }

        changedFlag = false;
        newFlag = false;
    }
}
 
