// Generated by OABuilder
package com.template.model.oa.propertypath;
 
import com.template.model.oa.*;
 
public class AppUserPP {
    private static AppUserLoginPPx appUserLogins;
     

    public static AppUserLoginPPx appUserLogins() {
        if (appUserLogins == null) appUserLogins = new AppUserLoginPPx(AppUser.P_AppUserLogins);
        return appUserLogins;
    }

    public static String id() {
        String s = AppUser.P_Id;
        return s;
    }

    public static String loginId() {
        String s = AppUser.P_LoginId;
        return s;
    }

    public static String password() {
        String s = AppUser.P_Password;
        return s;
    }

    public static String admin() {
        String s = AppUser.P_Admin;
        return s;
    }

    public static String superAdmin() {
        String s = AppUser.P_SuperAdmin;
        return s;
    }

    public static String editProcessed() {
        String s = AppUser.P_EditProcessed;
        return s;
    }

    public static String firstName() {
        String s = AppUser.P_FirstName;
        return s;
    }

    public static String lastName() {
        String s = AppUser.P_LastName;
        return s;
    }

    public static String inactiveDate() {
        String s = AppUser.P_InactiveDate;
        return s;
    }

    public static String note() {
        String s = AppUser.P_Note;
        return s;
    }

    public static String fullName() {
        String s = AppUser.P_FullName;
        return s;
    }

    public static String displayName() {
        String s = AppUser.P_DisplayName;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
