// Generated by OABuilder
package com.template.model.oa.propertypath;
 
import java.io.Serializable;
import com.template.model.oa.*;
 
public class ReportClassPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ReportClassPPx(String name) {
        this(null, name);
    }

    public ReportClassPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ReportPPx calcReports() {
        ReportPPx ppx = new ReportPPx(this, ReportClass.P_CalcReports);
        return ppx;
    }

    public ReportDefPPx reportDefs() {
        ReportDefPPx ppx = new ReportDefPPx(this, ReportClass.P_ReportDefs);
        return ppx;
    }

    public String id() {
        return pp + "." + ReportClass.P_Id;
    }

    public String created() {
        return pp + "." + ReportClass.P_Created;
    }

    public String name() {
        return pp + "." + ReportClass.P_Name;
    }

    public String className() {
        return pp + "." + ReportClass.P_ClassName;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
