// Generated by OABuilder
package com.template.model.oa.propertypath;
 
import java.io.Serializable;
import com.template.model.oa.*;
 
public class ReportDefPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ReportDefPPx(String name) {
        this(null, name);
    }

    public ReportDefPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ReportClassPPx reportClass() {
        ReportClassPPx ppx = new ReportClassPPx(this, ReportDef.P_ReportClass);
        return ppx;
    }

    public ReportPPx reports() {
        ReportPPx ppx = new ReportPPx(this, ReportDef.P_Reports);
        return ppx;
    }

    public String id() {
        return pp + "." + ReportDef.P_Id;
    }

    public String created() {
        return pp + "." + ReportDef.P_Created;
    }

    public String name() {
        return pp + "." + ReportDef.P_Name;
    }

    public String template() {
        return pp + "." + ReportDef.P_Template;
    }

    public String seq() {
        return pp + "." + ReportDef.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
