// Generated by OABuilder 
package com.template.view.client.panel.server;

import java.util.logging.*;

public class ServerBar extends ServerBarBase {
    private static Logger LOG = Logger.getLogger(ServerBarBase.class.getName());
}
