// Generated by OABuilder 
package com.template.view.client.panel.server;

import java.util.logging.Logger;

public class ServerPanel extends ServerPanelBase {
    private static Logger LOG = Logger.getLogger(ServerPanel.class.getName());
}
