// Generated by OABuilder 
package com.template.view.client.panel.reportDesigner;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.Logger;
import javax.swing.*;
import com.template.model.oa.*;
import com.template.model.oa.propertypath.*;
import com.template.delegate.*;
import com.template.model.search.*;
import com.template.resource.Resource;
import com.template.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.border.ShadowBorder;

public class ReportDesignerPanelBase {
    private static Logger LOG = Logger.getLogger(ReportDesignerPanelBase.class.getName());
    
    private JRadioButtonMenuItem mi; 
    private JToggleButton toggleButton;
    
    private JSplitPane splitPane;
    private OAOutlookBar outlookBar;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    
    public static final String CARD_ReportDesignerBar = "ReportDesignerBar";
    
    protected ReportDesignerBar barReportDesigner;
    
    public ReportDesignerPanelBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        splitPane = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, getOutlookBar(), cardPanel);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(.05d);
        
        ImageIcon icon;
        icon = Resource.getJarIcon("reportDesignerBar.png");
        outlookBar.addBar(CARD_ReportDesignerBar, "Report Designer", icon, new JScrollPane(getReportDesignerBar().getTree()));
        cardPanel.add(getReportDesignerBar().getPanel(), CARD_ReportDesignerBar);
    }
    
    public ReportDesignerBar getReportDesignerBar() {
        if (barReportDesigner != null) return barReportDesigner;
        barReportDesigner = new ReportDesignerBar();
        return barReportDesigner;
    }
    
    public OAOutlookBar getOutlookBar() {
        if (outlookBar != null) return outlookBar;
        outlookBar = new OAOutlookBar() {
            @Override
            protected void onBarSelected(String barName) {
                cardLayout.show(cardPanel, barName);
            }
        };
        int w = OAJfcUtil.getCharWidth(23);
        outlookBar.setPreferredSize(new Dimension(w, 50));
        outlookBar.setBorder(new ShadowBorder());
        Dimension d = outlookBar.getMinimumSize();
        w = OAJfcUtil.getCharWidth(1);
        d.width = w;
        outlookBar.setMinimumSize(d);
        outlookBar.setMinimumSize(new Dimension(10,10));
        return outlookBar;
    }
    
    public JToggleButton getToggleButton() {
        if (toggleButton != null) return toggleButton;
        toggleButton = new JToggleButton("Report Designer");
        ImageIcon ii = Resource.getJarIcon("reportDesignerButton.png");
        toggleButton.setIcon(ii);
        toggleButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toggleButton.setHorizontalTextPosition(SwingConstants.CENTER);
        toggleButton.setMnemonic('R');
        toggleButton.setToolTipText("show the Report Designer panel");
        return toggleButton;
    }
    
    public JRadioButtonMenuItem getMenuItem() {
        if (mi != null) return mi;
        mi = new JRadioButtonMenuItem();
        mi.setMnemonic(KeyEvent.VK_R);
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_R, InputEvent.ALT_MASK, false));
        mi.setText("Report Designer panel");
        mi.setToolTipText("show the ReportDesigner panel");
        return mi;
    }
    
    public JSplitPane getSplitPane() {
        return splitPane;
    }
    public JComponent getMainComponent() {
        return splitPane;
    }
}

