// Generated by OABuilder 
package com.template.view.client.panel.reportDesigner;

import java.util.logging.Logger;

public class ReportDesignerPanel extends ReportDesignerPanelBase {
    private static Logger LOG = Logger.getLogger(ReportDesignerPanel.class.getName());
}
