// Generated by OABuilder 
package com.template.view.client.panel.reportDesigner;

import java.util.logging.*;

public class ReportDesignerBar extends ReportDesignerBarBase {
    private static Logger LOG = Logger.getLogger(ReportDesignerBarBase.class.getName());
}
